spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # database connection credential
    url:  jdbc:mysql://sql3.freesqldatabase.com:3306/sql3521049
    username: sql3521049
    password: yig48bFyWG

    # config jpa
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          ddl-auto: create-drop
          use-new-id_generator-mappings: false
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
app:
  jwt:
    secret: abcdefghijkk
    header: Authorization
