spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # database connection credential
    url: jdbc:mysql://eventweb.mysql.database.azure.com:3306/web?useSSL=true
    username: event_plaza_619
    password: u7nB49cULC@gU


    # config jpa
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.hibernate.sql: DEBUG
app:
  jwt:
    secret: abcdefghijkk
    header: Authorization


