spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # database connection credential
    url:  jdbc:mysql://sql3.freesqldatabase.com:3306/sql3521049
    username: sql3521049
    password: yig48bFyWG

    # config jpa
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          ddl-auto: create-drop
app:
  jwt:
    secret: abcdefghijkk
    header: Authorization
