spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # database connection credential
    url: jdbc:mysql://eventweb.mysql.database.azure.com:3306/web?useSSL=true
    username: event_plaza_619
    password: u7nB49cULC@gU


    # config jpa
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          enable_lazy_load_no_trans: true

#  mail:
#    host: smtp.163.com #SMTP服务器地址
#    username: 13202381561 #登陆账号
#    password: KYDTVEZMUUUXPXKH #登陆密码（或授权码）
#    properties:
#      from: 13202381561@163.com #邮件发信人（即真实邮箱）
#    thymeleaf:
#      cache: false
#      prefix: classpath:/views/
#    servlet:
#      multipart:
#        max-file-size: 10MB #限制单个文件大小
#        max-request-size: 50MB #限制请求总量
logging:
  level:
    org.hibernate.sql: DEBUG
app:
  jwt:
    secret: abcdefghijkk
    header: Authorization